---
title: "smallcount i/o comparison"
shorttitle: "check on scuttle"
date: "`r format(Sys.time(), '%B %d, %Y')`"
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{smallcount}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document:
    highlight: pygments
    number_sections: yes
    theme: united
    toc: yes
---

# Genes in rows

## Setup

```{r code}
suppressPackageStartupMessages({
library(smallcount)
library(bench)
library(Matrix)
library(scuttle)
})
```
 
Define a function that retrieves dgCmatrix from CSV using Rafa's script

```{r mkfun}
raf1 = function() {
read_sparse_csv(system.file("extdata/tenx_subset.csv.gz", package="smallcount"))
}
```

Benchmark it


```{r run2}
mark( raf1(), iterations=2)
```

Benchmark Aaron's code in scuttle

```{r doscut}
doaaron = function() {
con = gzfile(system.file("extdata/tenx_subset.csv.gz", package="smallcount"), "r" )
on.exit(close(con))
readSparseCounts(con, sep=",")
}
mark(doaaron(), iterations=2)
```

Armadillo-based C++

Here we use unix utilities to remove header and gene names preparatory to
a simple C++-based import and conversion

```{r docxx}
 pa = system.file("extdata/tenx_subset.csv.gz", package="smallcount")
 tf = tempfile()
 file.copy(pa, tf)
 file.rename(tf, ntf <- paste0(tf, ".gz"))
 system(paste("gunzip", ntf)) # restores tf as gunzipped pa
 tf2 = tempfile()
 system(sprintf("sed -e '1,1d' %s | cut -d ',' -f 2- > %s", tf, tf2))
 bench::mark(mm <- parse_sparse_csv(tf2), iterations=2)
 dim(mm$sp)
```



# Genes in columns

Use rafa script

```{r runtr}
raf2 = function() {
read_sparse_csv_transpose(system.file("extdata/tenx_subset-transpose.csv.gz", package="smallcount"))
}
mark( raf2(), iterations=2)
```

Aaron:

```{r aartr}
doaaron_t = function() {
con = gzfile(system.file("extdata/tenx_subset-transpose.csv.gz", package="smallcount"), "r" )
on.exit(close(con))
readSparseCounts(con, sep=",")
}
mark(doaaron_t(), iterations=2)
```

Armadillo:


```{r docxxt}
 pa = system.file("extdata/tenx_subset-transpose.csv.gz", package="smallcount")
 tf = tempfile()
 file.copy(pa, tf)
 file.rename(tf, ntf <- paste0(tf, ".gz"))
 system(paste("gunzip", ntf)) # restores tf as gunzipped pa
 tf2 = tempfile()
 system(sprintf("sed -e '1,1d' %s | cut -d ',' -f 2- > %s", tf, tf2))
 bench::mark(mm <- parse_sparse_csv(tf2), iterations=2)
 dim(mm$sp)
```
