# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppReadSparseMatrix <- function(sample, barcode_col_names, id_row_names, genome, use_features_tsv) {
    .Call('_smallcount_cppReadSparseMatrix', PACKAGE = 'smallcount', sample, barcode_col_names, id_row_names, genome, use_features_tsv)
}

cppPoissonDevianceTransformation <- function(svt, mu) {
    .Call('_smallcount_cppPoissonDevianceTransformation', PACKAGE = 'smallcount', svt, mu)
}

cppPoissonDispersionTransformation <- function(svt, mu) {
    .Call('_smallcount_cppPoissonDispersionTransformation', PACKAGE = 'smallcount', svt, mu)
}

