# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_sparse_csv_impl <- function(fname) {
    .Call('_smallcount_parse_sparse_csv_impl', PACKAGE = 'smallcount', fname)
}

